@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.animalcrops.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
