modLoader="javafml" #mandatory
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/KnightMiner/AnimalCrops/issues/"
license="MIT"

[[mods]]
    modId="animalcrops" #mandatory
    version="${version}"
    displayName="Animal Crops"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/animal-crops"
    logoFile="animalcrops.png"
    credits=""
    authors="KnightMiner"
    description='''
    Adds crops that slowly grow baby animals.
    '''

[[dependencies.inspirations]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.inspirations]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
