modLoader="javafml" #mandatory
loaderVersion="[27,)"
issueTrackerURL="https://github.com/KnightMiner/AnimalCrops/issues/"
[[mods]]
    modId="animalcrops" #mandatory
    version="${file.jarVersion}"
    displayName="Animal Crops"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/animal-crops"
    logoFile="animalcrops.png"
    credits=""
    authors="KnightMiner"
    description='''
    Adds crops that slowly grow baby animals.
    '''

[[dependencies.inspirations]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.19,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.inspirations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,]"
    ordering="NONE"
    side="BOTH"
