@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.animalcrops.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
