@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.animalcrops.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
